### ISSUE TITLE
Hosting?

### ISSUE THREAD

**Issue by darlkr** [etesync/journal-manager#1]
Hey, very interesting project. Are you thinking of doing like a setup guide for hosting your own version of this once the code as been audited and is stable?

I'm thinking of setting up my own server and having this for private use could be fun.

**Comment by tasn** [comment]
Hey,

Sorry for the delayed reply, I'm away on holiday. There's a quick how-to in the README that should cover most of it.
As for a proper guide: to be honest, I don't have time to spare on this, I'd rather focus on improving the app and server.

Please let me know if you're having any issues getting it to work, I'll happily help.
